export const menuslyt = [
	{
		cacheFlag: false,
		children: undefined,
		code: 'sale_management',
		hidden: true,
		icon: 'order_list',
		name: '买家/卖家等待平台处理',
		parentCode: 'order',
		parentCodes: null,
		route: '/order/sale_management/index',
	},
	{
		cacheFlag: false,
		children: undefined,
		code: 'plate_refund',
		hidden: true,
		icon: 'order_list',
		name: '平台发起退款',
		parentCode: 'order',
		parentCodes: null,
		route: '/order/sale_management/plate_refund',
	},
	{
		cacheFlag: false,
		children: undefined,
		code: 'order_sale',
		hidden: false,
		icon: 'order_sale',
		name: '售后管理',
		parentCode: 'order',
		parentCodes: null,
		route: '/order/order_sale',
	},
	// {
	// 	cacheFlag: false,
	// 	children: undefined,
	// 	code: 'sale_management',
	// 	hidden: false,
	// 	icon: 'order_sale',
	// 	name: '平台发起退款',
	// 	parentCode: 'order',
	// 	parentCodes: null,
	// 	route: '/order/sale_management',
	// },
	{
		cacheFlag: false,
		children: undefined,
		code: 'sale_detail',
		hidden: true,
		icon: 'order_sale',
		name: '买家/卖家发起退款详情',
		parentCode: 'order',
		parentCodes: null,
		route: '/order/sale_detail',
	},
	{
		cacheFlag: false,
		children: undefined,
		code: 'buy_record',
		hidden: false,
		icon: 'shop-total',
		name: '交易记录',
		parentCode: 'order',
		parentCodes: null,
		route: '/order/buy_record/index',
	},
	{
		cacheFlag: false,
		children: undefined,
		code: 'shop_detail',
		hidden: true,
		name: '店铺结算详情',
		parentCode: 'order',
		parentCodes: null,
		route: '/order/buy_record/shop_detail',
	},
	{
		cacheFlag: false,
		children: undefined,
		code: 'order_detail',
		hidden: true,
		name: '账单明细',
		parentCode: 'order',
		parentCodes: null,
		route: '/order/buy_record/order_detail',
	},
	{
		cacheFlag: false,
		children: undefined,
		code: 'order_list',
		hidden: true,
		name: '账单明细列表',
		parentCode: 'order',
		parentCodes: null,
		route: '/order/buy_record/common/order_list',
	},
	{
		cacheFlag: false,
		children: undefined,
		code: 'evaluation_management',
		hidden: false,
		icon: 'evaluation_management',
		name: '评价管理',
		parentCode: 'order',
		parentCodes: null,
		route: '/order/evaluation_management',
	},
	{
		cacheFlag: true,
		code: 'review_info',
		hidden: true,
		icon: 'review_info',
		name: '评论信息',
		parentCode: 'order',
		parentCodes: null,
		route: '/order/evaluation_management/review_info',
	},
	{
		cacheFlag: false,
		children: undefined,
		code: 'trading_record',
		hidden: false,
		icon: 'trading_record',
		name: '交易流水',
		parentCode: 'order',
		parentCodes: null,
		route: '/order/trading_record',
	},
	{
		cacheFlag: true,
		code: 'data_center_download',
		hidden: false,
		icon: 'data_center_download',
		name: '渠道下载统计',
		parentCode: 'data_center',
		parentCodes: null,
		route: '/platform/dashboard/data_center/data_center_download',
	},
	{
		cacheFlag: true,
		code: 'statistical_details',
		hidden: true,
		icon: 'statistical_details',
		name: '统计详情',
		parentCode: 'order',
		parentCodes: null,
		route: '/platform/dashboard/data_center/data_center_download/statistical_details',
	},
]